[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "geolocation=(self)"
    X-Frame-Options = "DENY"
    X-Robots-Tag = "noindex"

[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200
  force = true

[[redirects]]
  from = "/index.html"
  to = "/app"
  status = 301
  force = true

[[redirects]]
  from = "/home.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true
